version: "3"
services:
  web:
    container_name: web
    build: ./
    depends_on:
      - redis
      - mysql
      - elasticsearch
    env_file: .env
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"
    volumes:
    - ".data/web:/app/logs"
    command: gunicorn -w 1 -b :5000 wsgi:app

    restart: always

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - "./data/nginx:/var/log/nginx"
    ports:
      - "80:80"
    depends_on:
      - web

  redis:
    container_name: redis
    image: redis
    # ports:
    #   - "6379:6379"
    expose:
      - "6379"
    volumes:
      - "./data/redis:/data"
    restart: always
    command: redis-server --appendonly yes

  mysql:
#    image: "docker.io/mysql:5"
    container_name: mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 4399
      MYSQL_USER: test
      MYSQL_PASS: 4399
      MYSQL_DATABASE: movies_recommend_system
    expose:
      - "3306"
    restart: always
    volumes:
      - "./data/mysql:/var/lib/mysql"
#      - "./mysql/my.cnf:/etc/my.cnf"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--max_allowed_packet=1024*1024*16']

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: web_elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - "./data/elasticsearch:/usr/share/elasticsearch/data"
    expose:
      - "9200"
      - "9300"
    restart: always
